FROM golang:1.15

ENV TERRAFORM_VERSION 0.13.5

RUN apt-get update \
 && apt-get install -y unzip \
 && cd /tmp \
 && wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
 && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
 && mv terraform /usr/local/bin/

RUN terraform version